#Configuation for robot odometry EKF
#
odom_frame: odom
base_link_frame: base_link
world_frame: odom
frequency: 50


odom0: jackal_velocity_controller/odom
# x, y, z, r, p, yaw, dx, dy, dz, dr, dp, dyaw, d^2 x, d^2 y, d^2 z, d^2 r, d^2 p, d^2 yaw
odom0_config: [false, false, false,
              false, false, false,
              true, true, true,
              false, false, true,
              false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true




